### PR TITLE
Data access and interface and data base

### LINKED ISSUE #5: Framework: Data Access, Data Access Interface, & Data Base
Includes DataAccessInterface, LeaderboardDataAccess, DataBase

DataAccessInterface: Moves data between UseCase and Leaderboard Data access
LeaderboardDataAccess: Fetches data from leaderboard file, Updates data from leaderboard file, Interacts with the interface
DataBase: file that contains user data

### PR DESCRIPTION
**Pull request by 123HenryLiu**
Created data access interface and data access read and write methods

### CODE REVIEW

**Review by Baehr3 — CHANGES_REQUESTED** [review]
Public access modifier is redundant for method headers in the interface.
instead of throwing IOExceptions up and not having it handled. May be better to try-catch and having it handled

**Review by NotSakura — COMMENTED** [review]
I don't see any major problems but if there is a better way to make the import statements I think that would clean up the code!

**Review by Baehr3 — APPROVED** [review]
Requests mentioned before has been fixed. Good Work!

**Review by NotSakura — APPROVED** [review]
This looks good to me!

**Review by ivyparc — APPROVED** [review]
Thorough use of try and catch blocks. Good use of override methods used to implement the interface.

**Pull request merged**
