### PR TITLE
2 main menu

### LINKED ISSUE #2: View: Main Menu
The main menu shows when the game of rack-up-grades begins. Framework with View, implemented by View Module.

### PR DESCRIPTION
**Pull request by Cathynvrdie**
main menu 1.2

### CODE REVIEW

**Review by NotSakura — APPROVED** [review]
This looks like a good start to our UI part of our game

**Review by Baehr3 — APPROVED** [review]
Creates a working Main Menu and buttons work for actions. Images will be needed later

**Comment by 123HenryLiu** [comment]
Good code

**Review by 123HenryLiu — APPROVED** [review]
Good code

**Review by ivyparc — APPROVED** [review]
Great use of Swing to create the UI of the game. No apparent issue spotted so far.

**Pull request merged**
