### PR TITLE
Hard game

### PR DESCRIPTION
**Pull request by Baehr3**
Hard has been implemented, working. This branch is newer than main.
Fixed issues with the leaderboard not working (not adding).
Refactored code for better packaging (suggestion by TA)
fixed all issues that came with refactoring.

### CODE REVIEW

**Review by NotSakura — DISMISSED** [review]
I think the changes look good. The javadocs seem to be alright as well and game seems to run.

**Review by NotSakura — DISMISSED** [review]
This looks good to me. The Javadocs are well written and all the tests pass. We fixed the bug in the add to leaderboard. The new class LeaderboardUseCase looks good as well. No code smells or CA or SOLID violations

**Review by Cathynvrdie — DISMISSED** [review]
Now we have an LP stuff.
And also we change the way to write in the icon and background images.
The named part for buttons has been replaced, which is good.
Andy and Sakura rewrite the Main Menu and UI stuff :]
Thanks.

**Review by 123HenryLiu — COMMENTED** [review]
the new methods look good
program runs fine as well
overall. no mistakes and changes seem useful

**Review by 123HenryLiu — APPROVED** [review]
the new methods look good
program runs fine as well
overall. no mistakes and changes seem useful

**Review by NotSakura — APPROVED** [review]
The only change I see is that the game now runs a full round instead of 10s for testing purposes. I think it looks good!

**Review by ivyparc — APPROVED** [review]
Extra methods were appropriately added in use case classes and UI files to handle errors with timer, etc. Tests are thoroughly implemented making sure each core part of the program executes without error. Thanks for the great work.

**Pull request merged**
