### PR TITLE
All entites to main so UseCase can access it 

### PR DESCRIPTION
**Pull request by NotSakura**
This is the Game entity and the negative objects (positive object to be added later)

### CODE REVIEW

**Review by Baehr3 — DISMISSED** [review]
Merge does not conflict with any previous code

**Review by 123HenryLiu — CHANGES_REQUESTED** [review]
Shouldn't have float value for point

**Review by 123HenryLiu — DISMISSED** [review]
Good work, point is now fixed

**Review by Baehr3 — CHANGES_REQUESTED** [review]
array lists are not required, use case pre-generates the game.

**Review by Baehr3 — APPROVED** [review]
ArrayList changes made.

**Review by ivyparc — APPROVED** [review]
Good use of abstract class for temporary purpose. Precaution is thoroughly taken care of in NegativeObj constructor.

**Review by 123HenryLiu — APPROVED** [review]
Good work, negative obj is now fixed

**Pull request merged**
