### PR TITLE
Game usecase and difficulty use cases

### PR DESCRIPTION
**Pull request by ivyparc**
GameUseCase is complete for its features and needs connection with presenters after this pull request

### CODE REVIEW

**Review by NotSakura — COMMENTED** [review]
If we no longer need Timer.java then we can probably get rid of it! I also didn't see any problems with clean architecture at=s it only depends on the Entities. Just add javadocs before we submit it!

**Review by Baehr3 — COMMENTED** [review]
Delete gradle/wrapper

**Review by Baehr3 — APPROVED** [review]
Initial merge to main.

**Review by NotSakura — APPROVED** [review]
Its great that the timer and gradel has been deleted and i still dont see any major SOLID issues (pun intended :) )

**Review by 123HenryLiu — APPROVED** [review]

**Pull request merged**
