### PR TITLE
Hard game

### PR DESCRIPTION
**Pull request by Baehr3**
THIS MAY BE THE FINAL PULL REQUEST. MORE TESTS WERE ADDED AND COVERAGE IS GENERATED.
PLEASE COMMENT ON THIS FINAL VERSION. FOCUS ON TESTS AND CHANGES IN USECASE. IGNORE COVERAGE HTML FILES THAT ARE ADDED

### CODE REVIEW

**Review by 123HenryLiu — DISMISSED** [review]
tests all look good

**Review by NotSakura — APPROVED** [review]
Sorry i keep pushing. I'm just adding little details so we can run the tests and the player is able to score low but still end up on the leaderboard. But it looks good. i played all 3 levels and it loos great!!

**Review by Cathynvrdie — APPROVED** [review]
Thank everyone for coding this final submission.
There are lots of tests that have been updated.
Anyway cool.

**Review by ivyparc — APPROVED** [review]
Methods have been added for testing purposes. Great work!

**Pull request merged**
