### PR TITLE
7 input boundary interface

### LINKED ISSUE #7: Input Boundary Interface & its Implementation
To ensure dependency inversion takes controllers input values and passes it to use case

### PR DESCRIPTION
**Pull request by Baehr3**
Completed input boundary that works together with controller. The UseCase will store: InputBoundary i = new InputBoundaryImpl();
which does not violate CA because the InputBoundaryImpl is in the same layer as UseCase. A pull request will be made for controllers also

### CODE REVIEW

**Review by NotSakura — APPROVED** [review]
I think the Input boundary looks good: It's not violating SOLID and there aren't any big code smells here

**Review by NotSakura — APPROVED** [review]
I think the Input boundary looks good: It's not violating SOLID and there aren't any big code smells here

**Review by ivyparc — APPROVED** [review]
Thoroughly implemented to help with dependency inversion

**Review by Cathynvrdie — APPROVED** [review]
cool

**Pull request merged**
