### PR TITLE
10 game engine positive object

### LINKED ISSUE #10: Entity: Positive Object (a.k.a "Assignment")
Create the Positive Object Class on the class
To the user, it is an assignment

Responsibilities:

Tries to hit it before it goes down
Stores positive points based on constructor

### PR DESCRIPTION
**Pull request by 123HenryLiu**
created positive object class

### CODE REVIEW

**Review by Baehr3 — APPROVED** [review]
The positive object is complete and correlates with negative object. Do make sure to add comments or javadoc later before milestone submission

**Review by NotSakura — CHANGES_REQUESTED** [review]
I'm just adding this just for the sake of it btw: I think this is done as long as you add the javadoc

**Review by NotSakura — APPROVED** [review]
This looks good! Just add javadocs

**Review by Cathynvrdie — CHANGES_REQUESTED** [review]
cool

**Review by Cathynvrdie — APPROVED** [review]
cool

**Pull request merged**
