### PR TITLE
43 design pattern facade for setting name add to leaderboard

### LINKED ISSUE #43: Design Pattern: Facade for setting name & add to leaderboard
## Add to leaderboard fix for the game. From view to navigator to usecase. In the form of a facade

### PR DESCRIPTION
**Pull request by NotSakura**
able to now play multiple games with the previous game continuing

### CODE REVIEW

**Review by ivyparc — DISMISSED** [review]
Good job in catching errors and using if statements logically.

**Review by Baehr3 — DISMISSED** [review]
Nice work! On Facade, and documenting usecase

**Review by Cathynvrdie — APPROVED** [review]
I found that we implement the method of the time, pts. connect the player info data for the leaderboard. Nice.

**Review by Cathynvrdie — DISMISSED** [review]
Sally the god.
The new upload: game frame close after "add to leadboard".
Time and pts can show up on the game screen.
cool.

**Review by Baehr3 — APPROVED** [review]
AddToLeaderboard is fixed may require additional testing

**Review by NotSakura — COMMENTED** [review]
I think this looks good. Especially good that we were able to add a facade but tmr we will need to test it under the edge and unit cases to see if it's alright. Other than that Javadoc is the only thing missing so we are good to go!

**Review by ivyparc — APPROVED** [review]

**Review by 123HenryLiu — APPROVED** [review]
new photos look good and code seems to work

**Pull request merged**
